name: Run Sonar Scanner

description: Run Sonar Scanner

inputs:
  github-repo-name:
    required: true
    description: Repo Name
  GITHUB_TOKEN:
    required: true
    description: GITHUB_TOKEN
  SONAR_TOKEN:
    required: true
    description: SONAR_TOKEN

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Download code coverage results
      uses: actions/download-artifact@v3

    - uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
