name: Run Sonar Scanner

description: Run Sonar Scanner

inputs:
  github-repo-name:
    required: true
    description: Repository name

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Download code coverage results
      uses: actions/download-artifact@v3

    - name: "Move coverage file to correct folder"
      run: sed -i 's+/home/runner/work/${{ inputs.github-repo-name }}/${{ inputs.github-repo-name }}+/github/workspace+g' htmlcov/index.html
      shell: bash

    - uses: SonarSource/sonarcloud-github-action@master
