name: Run Sonar Scanner

description: Run Sonar Scanner

runs:
  using: "composite"
  steps:
    
    - uses: actions/checkout@v3
    
    - name: Download code coverage results
      uses: actions/download-artifact@v3

    - name: "Move coverage file to correct folder"
      run: sed -i 's+/home/runner/work/${{env.REPO_NAME}}/${{env.REPO_NAME}}+/github/workspace+g' code-coverage-report/coverage.xml
      shell: bash
    
    - uses: SonarSource/sonarcloud-github-action@master
