name: Run Sonar Scanner

description: Run Sonar Scanner

inputs:
  github-repo-name:
    required: true
    description: Repo Name
  GITHUB_TOKEN:
    required: true
    description: GITHUB_TOKEN
  SONAR_TOKEN:
    required: true
    description: SONAR_TOKEN

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Download code coverage results
      uses: actions/download-artifact@v3

    - name: "Move coverage file to correct folder"
      run: sed -i 's+/home/runner/work/${{ inputs.github-repo-name }}/${{ inputs.github-repo-name }}+/github/workspace+g' code-coverage-report/lcov.info
      shell: bash
    
    - uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: "7e46568cf99751eaee7b5a98824e211c10e47a46"

    # - name: SonarQube Quality Gate check
    #   id: sonarqube-quality-gate-check
    #   uses: sonarsource/sonarqube-quality-gate-action@master
    #   env:
    #    SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
